---
language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
script: bundle exec rspec spec
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5.0.gemfile
